BEGIN TRANSACTION;


DROP TABLE IF EXISTS dbo.Statistics;
DROP TABLE IF EXISTS dbo.Games;
DROP TABLE IF EXISTS dbo.Tokens;
DROP TABLE IF EXISTS dbo.Lobbies;
DROP TABLE IF EXISTS dbo.Users;

DROP SCHEMA IF EXISTS dbo;


COMMIT;